#+title: GNU Emacs configuration
#+author: mayrf
#+email: 70516376+mayrf@users.noreply.github.com
#+language: en
#+startup: content indent

This is my WIP vanilla Emacs config. The structure and content is heavily copied from Protesilaos Stavrous' [[https://protesilaos.com/emacs/dotemacs][dotemacs config]] and I am very grateful to him for sharing all of his superb Emacs resources with the community.

* The early initialisation of Emacs (=early-init.el=)

#+begin_src emacs-lisp :tangle "early-init.el"
;; (setq package-enable-at-startup nil
;;      inhibit-startup-message   t
;;     frame-resize-pixelwise    t  ; fine resize
;;      package-native-compile    t ; native compile packages
;; )
(scroll-bar-mode -1)               ; disable scrollbar
(tool-bar-mode -1)                 ; disable toolbar
;; (tooltip-mode -1)                  ; disable tooltips
;; (menu-bar-mode -1)                 ; disable menubar
#+end_src

* The main initialisation of Emacs (=init.el=)
** Package Manager
*** Elpaca
**** NixOs specific fix
See [[https://github.com/progfolio/elpaca/wiki/Usage-with-Nix][Usage with Nix · progfolio/elpaca Wiki · GitHub]]
#+begin_src emacs-lisp :tangle "init.el"
(defun my/nixos-p ()
  "Return t if operating system is NixOS, nil otherwise."
  (string-match-p "NixOS" (shell-command-to-string "uname -v")))

(defun my/nixos/get-emacs-build-date ()
  "Return NixOS Emacs build date."
  (string-match "--prefix.*emacs.*\\([[:digit:]]\\{8\\}\\)" system-configuration-options)
  (string-to-number (match-string 1 system-configuration-options)))

;; Run this before the elpaca.el is loaded. Before the installer in your init.el is a good spot.
(when (my/nixos-p) (setq elpaca-core-date (list (my/nixos/get-emacs-build-date))))
;;(setq elpaca-core-date (list (my/nixos/get-emacs-build-date)))
#+end_src

**** Installation
#+begin_src emacs-lisp :tangle "init.el"
(defvar elpaca-installer-version 0.8)
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref nil :depth 1
                              :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                              :build (:not elpaca--activate-package)))
(let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
       (build (expand-file-name "elpaca/" elpaca-builds-directory))
       (order (cdr elpaca-order))
       (default-directory repo))
  (add-to-list 'load-path (if (file-exists-p build) build repo))
  (unless (file-exists-p repo)
    (make-directory repo t)
    (when (< emacs-major-version 28) (require 'subr-x))
    (condition-case-unless-debug err
        (if-let* ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                  ((zerop (apply #'call-process `("git" nil ,buffer t "clone"
                                                  ,@(when-let* ((depth (plist-get order :depth)))
                                                      (list (format "--depth=%d" depth) "--no-single-branch"))
                                                  ,(plist-get order :repo) ,repo))))
                  ((zerop (call-process "git" nil buffer t "checkout"
                                        (or (plist-get order :ref) "--"))))
                  (emacs (concat invocation-directory invocation-name))
                  ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                        "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                  ((require 'elpaca))
                  ((elpaca-generate-autoloads "elpaca" repo)))
            (progn (message "%s" (buffer-string)) (kill-buffer buffer))
          (error "%s" (with-current-buffer buffer (buffer-string))))
      ((error) (warn "%s" err) (delete-directory repo 'recursive))))
  (unless (require 'elpaca-autoloads nil t)
    (require 'elpaca)
    (elpaca-generate-autoloads "elpaca" repo)
    (load "./elpaca-autoloads")))
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca `(,@elpaca-order))
#+end_src

**** Configuration
#+begin_src emacs-lisp :tangle "init.el"
;; Install use-package support
(elpaca elpaca-use-package
  ;; Enable use-package :ensure support for Elpaca.
  (elpaca-use-package-mode))
(setq use-package-always-ensure t)
#+end_src

**** Do not show those confusing warnings when installing packages
#+begin_src emacs-lisp :tangle "init.el"
(add-to-list 'display-buffer-alist
             '("\\`\\*\\(Warnings\\|Compile-Log\\)\\*\\'"
               (display-buffer-no-window)
               (allow-no-window . t)))
#+end_src

** Custom Elisp
*** Auto tangle configuration
#+begin_src emacs-lisp :tangle "init.el"
(defun org-babel-tangle-config ()
  ;; (when (string-equal (buffer-file-name)
  ;; 		      (expand-file-name "~/.config/emacs-vanilla/mayrf-emacs.org"))
  (when (string-match "mayrf-emacs.org" (buffer-file-name))
    (let ((org-config-babel-evaluate nil))
      (org-babel-tangle))))

(add-hook 'org-mode-hook
	  (lambda ()
	    (add-hook 'after-save-hook #'org-babel-tangle-config)))
#+end_src

*** Reload config
#+begin_src emacs-lisp :tangle "init.el"

(defun load-directory (dir)
  (let ((load-it (lambda (f)
		   (load-file (concat (file-name-as-directory dir) f)))
		 ))
    (mapc load-it (directory-files dir nil "\\.el$"))))

(defun my/reload-emacs ()
  (interactive)
  ;; (org-babel-tangle "~/.config/emacs-vanilla/mayrf-emacs.org")
  (my/reload-init-el)
  (my/reload-modules))

(defun my/reload-init-el ()
  (load-file "~/.config/emacs-vanilla/init.el"))


(defun my/reload-modules ()
  (interactive)
  (load-directory (locate-user-emacs-file "mayrf-emacs-modules")))
;; (mapc
;;  (lambda (string)
;;    (add-to-list 'load-path (locate-user-emacs-file string)))
;;'("prot-lisp" "prot-emacs-modules"))
;;'("mayrf-lisp" "mayrf-emacs-modules"))
#+end_src

** The =init.el= arrangements for my own modules and custom libraries

I use a literate configuration as the "source of truth" for my Emacs
configuration. What I do is to specify everything in one file and
provide instructions for where things should go. The end product
consists of a large set of files, encompassing the =early-init.el=
([[#h:7b7b5898-09f7-4128-8af0-4041f67cb729][The early initialisation of Emacs (=early-init.el=)]]), the =init.el=
([[#h:dae63bd9-93a8-41c4-af1b-d0f39ba50974][The main initialisation of Emacs (=init.el=)]]), the modules of my
init, and the custom libraries I wrote.

In the code snippet further below, I add two directories to the
~load-path~. Concretely, any Emacs Lisp file inside these directories
is thus declared to Emacs and we can load it properly. Here is what
these two directories are about:

- The =prot-emacs-modules= directory :: This is where I store all the
  individual components of my Emacs setup. When I run Emacs, the
  directory is a subdirectory of =~/.emacs.d/=. All files are prefixed
  with =prot-emacs-=, followed by a word that broadly describes their
  scope of application, such as ~prot-emacs-font~, ~prot-emacs-window~...

  Each module consists of ordinary Elisp and a final call to ~provide~
  the set of configurations as a /feature/ that can then be loaded via
  ~require~ from the =init.el=. What Emacs calls a "feature" is, in
  essence, a variable whose value is the entirety of the file that has
  a ~provide~ call in it. Features are symbols that are named after
  the file name minus its file type extension: ~prot-emacs-theme~ is
  the feature provided by =prot-emacs-theme.el=.

  Modules are intended only for configuration purposes.  They do not
  define any major variables/functions, unless those are too
  small/specific to be extracted into their own library.

- The =prot-lisp= directory :: As with the aforementioned modules,
  this directory is a subdirectory of =~/.emacs.d/=. This is where I
  keep all my custom code that individual modules configure. The
  contents of this directory can be understood as fully fledged
  "packages" and, in fact, many of my actual packages started out as
  =prot-lisp= experiments.

  Each file is written in accordance with the conventions on Emacs
  packaging, even though they are only intended for use in my setup
  and are not polished to the level of my actual public-facing
  packages (meaning the ones listed here: <https://protesilaos.com/emacs>).

All this may not matter to you if you are reading either the
=prot-emacs.org= file or its web page version. Still, this arrangement
gives me maximum flexbility, as I can still share my code the way it
would look. Plus, if I ever decide to stop using the literate config,
I can simply stop editing it and perfom the edits directly in the
files that are already placed where I need them to be.

#+begin_src emacs-lisp :tangle "init.el"
  (mapc
   (lambda (string)
     (add-to-list 'load-path (locate-user-emacs-file string)))
   ;;'("prot-lisp" "prot-emacs-modules"))
   '("mayrf-lisp" "mayrf-emacs-modules"))
(require 'mayrf-emacs-keybindings)
(require 'mayrf-emacs-completion)
(require 'mayrf-emacs-style)
(require 'mayrf-emacs-org-mode)
(require 'mayrf-emacs-denote)
(require 'mayrf-emacs-magit)


#+end_src

** Evil mode
 #+begin_src emacs-lisp :tangle "init.el"
(use-package evil
  :ensure t
  :init
  (setq evil-want-integration t) ;; This is optional since it's already set to t by default.
  (setq evil-want-keybinding nil)
  :config
  (evil-mode 1))

(use-package evil-collection
  :after evil
  :ensure t
  :config
  (evil-collection-init))

(use-package evil-nerd-commenter
  :after evil
  :config
  (evilnc-default-hotkeys)
  (define-key evil-normal-state-map "gc" 'evilnc-comment-operator)
  (define-key evil-visual-state-map "gc" 'evilnc-comment-operator))
 #+end_src

** General Settings
*** Visual
#+begin_src emacs-lisp :tangle "init.el"
(global-visual-line-mode t)
#+end_src
*** Navigation
**** Minibuffer ESCAPE
By default, Emacs requires you to hit ESC three times to escape quit the minibuffer.
#+begin_src emacs-lisp :tangle "init.el"
(global-set-key [escape] 'keyboard-escape-quit)
#+end_src
*** Must have settings from System crafters:
https://systemcrafters.net/emacs-from-scratch/the-best-default-settings/
#+begin_src emacs-lisp :tangle "init.el"
    (recentf-mode 1)
      ;; Save what you enter into minibuffer prompts
    (setq history-length 25)
    (savehist-mode 1)
    ;; Remember and restore the last cursor location of opened files
    (save-place-mode 1)

    ;; Move customization variables to a separate file and load it
    ;; Disable the damn thing by making it disposable.
    (setq custom-file (make-temp-file "emacs-custom-"))
    (setq custom-file (locate-user-emacs-file "custom-vars.el"))
    (load custom-file 'noerror 'nomessage)

    ;; Don't pop up UI dialogs when prompting
    ;;(setq use-dialog-box nil)
    ;; Revert buffers when the underlying file has changed
    (global-auto-revert-mode 1)
    ;; Revert Dired and other buffers
    (setq global-auto-revert-non-file-buffers t)

#+end_src

#+begin_src emacs-lisp :tangle "init.el"
#+end_src
*** Themes:
#+begin_src emacs-lisp :tangle "init.el"
  (setq custom-safe-themes t)
  (use-package ef-themes
    :config
    (load-theme 'ef-melissa-dark t nil))
  ;;(load-theme 'ef-melissa-dark)
#+end_src

** PDFs
#+begin_src emacs-lisp :tangle "init.el"
(use-package pdf-tools
  :defer t
  :commands (pdf-loader-install)
  :mode "\\.pdf\\'"
  :bind (:map pdf-view-mode-map
              ("j" . pdf-view-next-line-or-next-page)
              ("k" . pdf-view-previous-line-or-previous-page)
              ("C-=" . pdf-view-enlarge)
              ("C--" . pdf-view-shrink))
  :init (pdf-loader-install)
  :config (add-to-list 'revert-without-query ".pdf"))

(add-hook 'pdf-view-mode-hook #'(lambda () (interactive) (display-line-numbers-mode -1)
                                                         (blink-cursor-mode -1)
                                                         ;; (doom-modeline-mode -1)
							 ))
#+end_src
* Style:
#+begin_src elisp :tangle "mayrf-emacs-modules/mayrf-emacs-style.el" :mkdirp yes
(use-package nerd-icons
  :ensure t)

(use-package nerd-icons-completion
  :ensure t
  :after marginalia
  :config
  (add-hook 'marginalia-mode-hook #'nerd-icons-completion-marginalia-setup))

(use-package nerd-icons-corfu
  :ensure t
  :after corfu
  :config
  (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter))

(use-package nerd-icons-dired
  :ensure t
  :hook
  (dired-mode . nerd-icons-dired-mode))

(provide 'mayrf-emacs-style)
#+end_src

* Key-bindings:
#+begin_src elisp :tangle "mayrf-emacs-modules/mayrf-emacs-keybindings.el" :mkdirp yes
(use-package general
  :config
  (general-evil-setup)
  (general-create-definer my/leader
    :states '(normal insert visual emacs)
    :keymaps 'override
    :prefix "SPC" ;; set leader
    :global-prefix "M-SPC") ;; access leader in insert mode
  (my/leader
    "b" '(:ignore t :wk "buffer")
    "bb" '(switch-to-buffer :wk "Switch buffer")
    "bk" '(kill-this-buffer :wk "Kill this buffer")
    "bn" '(next-buffer :wk "Next buffer")
    "bp" '(previous-buffer :wk "Previous buffer")
    "br" '(revert-buffer :wk "Reload buffer"))
  (my/leader
    "o" '(:ignore t :wk "Open")
    "oA" '(org-agenda :wk "Org Agenda"))

  (my/leader
    "f" '(:ignore t :wk "file")
    "ff" 'find-file
    "fr" 'recentf)

  (my/leader
    "h" '(:ignore t :wk "help")
    "hrr" 'my/reload-emacs
    "hy" 'my/reload-emacs
    "hf" '(describe-function :wk "Describe function")
    "hv" '(describe-variable :wk "Describe variable")
    "hk" '(describe-variable :wk "Describe key")))
#+end_src

#+begin_src elisp :tangle "mayrf-emacs-modules/mayrf-emacs-keybindings.el" :mkdirp yes
(provide 'mayrf-emacs-keybindings)

#+end_src

* completion:
#+begin_src elisp :tangle "mayrf-emacs-modules/mayrf-emacs-completion.el" :mkdirp yes
  (use-package vertico
    :ensure t
    :custom
    ;; (vertico-scroll-margin 0) ;; Different scroll margin
    (vertico-count 22) ;; Show more candidates
    ;; (vertico-resize t) ;; Grow and shrink the Vertico minibuffer
    ;; (vertico-cycle t) ;; Enable cycling for `vertico-next/previous'
    :init
    (vertico-mode))
#+end_src

#+begin_src elisp :tangle "mayrf-emacs-modules/mayrf-emacs-completion.el" :mkdirp yes

(use-package orderless
  :ensure t
  :custom
  (completion-styles '(orderless basic))
  (completion-category-overrides '((file (styles basic partial-completion)))))

(use-package marginalia
  ;; :hook (after-init . marginalia-mode))
  :config (marginalia-mode))
(provide 'mayrf-emacs-completion)
#+end_src

* Org-mode:
** Variable
#+begin_src elisp :tangle "mayrf-emacs-modules/mayrf-emacs-org-mode.el" :mkdirp yes
(setq org-src-preserve-indentation t)
(setq org-directory "~/Documents/org/")
(setq org-agenda-files (directory-files-recursively org-directory "\\.org$"))
#+end_src
** Keybindings
#+begin_src elisp :tangle "mayrf-emacs-modules/mayrf-emacs-org-mode.el" :mkdirp yes
#+end_src
** Org Babel

#+begin_src elisp :tangle "mayrf-emacs-modules/mayrf-emacs-org-mode.el" :mkdirp yes
(setq org-src-preserve-indentation t)
#+end_src

This goal of this section is to make emacs behave inside src blocks like in the major mode of the language specified by the src block
#+begin_src elisp :tangle "mayrf-emacs-modules/mayrf-emacs-org-mode.el" :mkdirp yes
(setq org-src-tab-acts-natively t)
#+end_src

#+begin_src elisp :tangle "mayrf-emacs-modules/mayrf-emacs-org-mode.el" :mkdirp yes
(provide 'mayrf-emacs-org-mode)
#+end_src
** org-caldav
#+begin_src elisp :tangle "mayrf-emacs-modules/mayrf-emacs-org-mode.el" :mkdirp yes
* Denote:
#+begin_src elisp :tangle "mayrf-emacs-modules/mayrf-emacs-denote.el" :mkdirp yes
(use-package denote
  :after org
  :config
  (setq denote-directory (file-truename (file-name-concat org-directory "Denotes/")))
  )
#+end_src

#+begin_src elisp :tangle "mayrf-emacs-modules/mayrf-emacs-denote.el" :mkdirp yes
(provide 'mayrf-emacs-denote)
#+end_src

* Magit:
#+begin_src elisp :tangle "mayrf-emacs-modules/mayrf-emacs-magit.el" :mkdirp yes
(use-package magit
  :after general
  :general (my/leader "gg" 'magit))
#+end_src

#+begin_src elisp :tangle "mayrf-emacs-modules/mayrf-emacs-magit.el" :mkdirp yes
(provide 'mayrf-emacs-magit)
#+end_src
