# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ ... }:

{
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.loader = {
    systemd-boot = {
      configurationLimit = 10;
      enable = true;
    };
    efi = { canTouchEfiVariables = true; };
  };
  services.fstrim.enable = true;

  # Power/cpu savings
  # https://nixos.wiki/wiki/Laptop
  # services.auto-cpufreq.enable = true;
  services.thermald.enable = true;
  services.system76-scheduler.settings.cfsProfiles.enable = true;
  hardware.graphics.enable32Bit = true;

  boot.initrd.availableKernelModules = [ "usb_storage" "sr_mod" ];
}
