{
  imports = [
    ./docker.nix
    ./gaming.nix
    ./impermanence.nix
    ./laptop.nix
    ./vpn.nix
    ./virtualisation.nix
    ./open-webui.nix
    ./keyd.nix
    ./kanata.nix
    ./sddm.nix
    ./pipewire.nix
    ./sops.nix
    ./theming.nix
    ./printing.nix
    ./flatpak.nix
    ./winapps.nix
    ./bluetooth.nix
    ./devbox.nix
  ];
}
